FROM python:3.9-slim

WORKDIR /home/api_train_content/

# Copy necessary files
COPY ./training/requirements.txt .
COPY ./training/api_train_content.py .
COPY ./tfidf_vectorizer_model/__init__.py .
COPY ./tfidf_vectorizer_model/tfidf_vectorizer_model.py .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Use ARG to accept build-time variable
ARG TRAINING_PORT
# ENV PORT=${DATABASE_PORT}

# Expose the application port
EXPOSE ${TRAINING_PORT}
RUN echo "The training port is: ${TRAINING_PORT}"

# Run the application
CMD ["sh", "-c", "uvicorn api_train_content:app --host 0.0.0.0 --port ${TRAINING_PORT}"]