FROM python:3.9-slim

WORKDIR /home/api_train_content/

# Copy necessary files
COPY ./training/requirements.txt .
COPY ./training/api_train_content.py .
COPY ./training/.env_git .
COPY ./tfidf_vectorizer_model/__init__.py .
COPY ./tfidf_vectorizer_model/tfidf_vectorizer_model.py .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 8090

# Run the application
CMD ["uvicorn", "api_train_content:app", "--host", "0.0.0.0", "--port", "8080"]