FROM continuumio/miniconda3
WORKDIR /home/api_train_content/
COPY environment.yml .
COPY api_train_content.py .
COPY .env_git .
RUN conda init bash
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "conda_env", "/bin/bash", "-c"]

EXPOSE 8080

# Run the application
CMD ["bash", "-c", "source activate conda_env && uvicorn api_train_content:app --host 0.0.0.0 --port 8080"]