FROM continuumio/miniconda3
WORKDIR /home/api_preprocess_content/
COPY environment.yml .
COPY api_preprocess_content.py .
COPY .env_git .
RUN conda init bash
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "conda_env", "/bin/bash", "-c"]

EXPOSE 9000

# Run the application
CMD ["bash", "-c", "source activate conda_env && uvicorn api_preprocess_content:app --host 0.0.0.0 --port 9000"]
