FROM python:3.9

WORKDIR /app

COPY preprocessing_content_based_mlflow.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "preprocessing_content_based_mlflow.py"]
