FROM continuumio/miniconda3
WORKDIR /home/jovyan/DB_api/
COPY environment.yml .
COPY db_api.py .
COPY .env_git .
RUN conda init bash
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "conda_env", "/bin/bash", "-c"]

RUN mkdir /home/jovyan/DB_api/processed_data
RUN mkdir /home/jovyan/DB_api/raw_data

EXPOSE 8000

# Run the application
CMD ["bash", "-c", "source activate conda_env && uvicorn db_api:app --host 0.0.0.0 --port 8000"]