FROM continuumio/miniconda3
WORKDIR /home/trainAPI/
COPY environment.yml .
COPY trainAPIcontent.py .
COPY .env_git .
RUN conda init bash
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "conda_env", "/bin/bash", "-c"]

EXPOSE 8080

# Run the application
CMD ["bash", "-c", "source activate conda_env && uvicorn trainAPIcontent:app --host 0.0.0.0 --port 8080"]