name: conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fastapi
  - pandas
  - numpy
  - httptools
  - uvloop 
  - uvicorn
  - pydantic
  - scikit-learn
  - requests
  - pip:
    - mlflow==2.9.2