FROM python:3.9-slim

WORKDIR /home/api_inference_content/

# Copy necessary files
COPY ./inference/requirements.txt .
COPY ./inference/api_inference_content.py .
COPY ./inference/.env_git .
COPY ./tfidf_vectorizer_model/__init__.py .
COPY ./tfidf_vectorizer_model/tfidf_vectorizer_model.py .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 8090

# Run the application
CMD ["uvicorn", "api_inference_content:app", "--host", "0.0.0.0", "--port", "8090"]