FROM python:3.9-slim

WORKDIR /home/api_train_content/

# Copy necessary files
COPY requirements.txt .
COPY api_train_content.py .
COPY .env_git .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["uvicorn", "api_train_content:app", "--host", "0.0.0.0", "--port", "8080"]