FROM python:3.9-slim

WORKDIR /home/api_database/

# Copy necessary files
COPY requirements.txt .
COPY api_database.py .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Create necessary directories
RUN mkdir /home/api_database/processed_data
RUN mkdir /home/api_database/raw_data

# Use ARG to accept build-time variable
ARG DATABASE_PORT
# ENV PORT=${DATABASE_PORT}

# Expose the application port
EXPOSE ${DATABASE_PORT}
RUN echo "The application port is: ${DATABASE_PORT}"

# Run the application
# Print the environment variable and run the application
CMD ["sh", "-c", "echo 'The application port is: ${DATABASE_PORT}' && uvicorn api_database:app --host 0.0.0.0 --port ${DATABASE_PORT}"]