FROM continuumio/miniconda3
WORKDIR /home/api_database/
COPY environment.yml .
COPY api_database.py .
COPY .env_git .
RUN conda init bash
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "conda_env", "/bin/bash", "-c"]

RUN mkdir /home/api_database/processed_data
RUN mkdir /home/api_database/raw_data

EXPOSE 8000

# Run the application
CMD ["bash", "-c", "source activate conda_env && uvicorn api_database:app --host 0.0.0.0 --port 8000"]