FROM python:3.9-slim

WORKDIR /home/api_database/

# Copy necessary files
COPY requirements.txt .
COPY api_database.py .
COPY .env_git .

# Install dependencies using pip
RUN pip install --no-cache-dir -r requirements.txt

# Create necessary directories
RUN mkdir /home/api_database/processed_data
RUN mkdir /home/api_database/raw_data

# Expose the application port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "api_database:app", "--host", "0.0.0.0", "--port", "8000"]